[helpers]

[settings]
default_target_type = 'symbolic'

[awesomewm]
depends = []

[awesomewm.files]
awesome = { target = '~/.config/awesome/', type = 'symbolic' }

[cmus.files]
'cmus/rc' = '~/.config/cmus/rc'

[fonts.files]
fonts = '~/.config/fonts'

[git.files]
'git/config' = '~/.gitconfig'

[hypr.files]
hypr = { target = '~/.config/hypr', type = "template" }
'hypr/files/background.png' = { target = '~/.config/hypr/files/background.png', type = "symbolic" }
'hypr/files/background.jpg' = { target = '~/.config/hypr/files/background.jpg', type = "symbolic" }

[nixos.files]
nixos = '/etc/nixos'

[nushell]
depends = []

[nushell.files]
nushell = '~/.config/nushell'

[nushell.variables]

[nvim]
depends = []

[nvim.files]
nvim = "~/.config/nvim"

[nvim.variables]

[starship.files]
starship = '~/.config/starship'

[sway.files]
sway = '~/.config/sway'

[waybar.files]
waybar = '~/.config/waybar'
[wezterm]
depends = []

[wezterm.files]
wezterm = { target = '~/.config/wezterm', type ="template" }

[wofi.files]
wofi = '~/.config/wofi'

[claude.files]
'claude/plugins' = '~/.claude/plugins/local'
